### ISSUE TITLE
priority repository

### ISSUE THREAD

**Issue by ahlrodrigues** [rg3/slackroll#12] opened 2018-06-12 22:20 UTC
Would it be possible to prioritize a repository for package installation? How would it be in the case of multilib?

**Comment by rg3** [comment] 2018-06-13 20:01
Can you provide a specific example use case for that functionality? Multiple repositories normally don't have the exact same packages, because they differ in the packager initials, at least, so slackroll's package selection interactive mechanism suffices. If not, by combining that with blacklists (mirror-specific or not) you usually get something workable.

**Comment by ahlrodrigues** [comment] 2018-06-13 23:37
In case we use the multilib layer of AlienBoB, the packages in the multilib directory must have priority over the official packages, so that multilib works and does not update the packages: official => multilib => official => multilib .... Look at this: https://docs.slackware.com/slackware:multilib

**Comment by rg3** [comment] 2018-06-16 09:49
I don't think that's what would happen, which is why I was asking for a specific example of things not working as expected. Correct me if I'm wrong at some point in the following text:

To get a multilib system, two steps are required. First of all, replacing the official gcc and glibc family of packages with those provided by AlienBOB. Then, installing a bunch of additional packages converted from Slackware 32 bits.

The second part is not problematic, or shouldn't be, because the 32-bit packages and compat32-tools have different actual names (libfoo vs libfoo-compat32) so they're effectively different packages and can be installed together.

The first part is not problematic as far as I know: slackroll does not consider a package as outdated unless your installed version does not match any remote version. So let's say you have glibc-solibs-3.0_multilib installed while the official version gets updated to glibc-solibs-3.1. slackroll won't prompt you to upgrade, because glibc-solibs-3.0_multlib would still be present in AlienBOB's mirror (naturally, you must refrain from installing other updates that may depend on this new glibc, but that's a problem known to multilib users that slackroll won't solve). A day or a couple of days later glibc-solibs-3.0_multilib will disappear and be replaced with glibc-solibs-3.1_multilib.

At that moment, your glibc-solibs package will finally be outdated and slackroll will ask you which version you want. It's supposed to tell you something like "You have glibc-solibs-3.0_multilib. Which version do you want to install?" and let you choose among the multilib and non-multilib versions, and you can choose the multilib version.

If you don't want to ever be asked about the non-multilib versions of glibc and gcc packages, it's a perfect case for using the blacklisting mechanism and ignoring glibc- and gcc- packages that do not mention multilib in their versions. You can do that using Python's negative lookahead regexp groups as part of the blacklist regular expression.

https://docs.python.org/2.7/library/re.html#regular-expression-syntax

**Comment by rg3** [comment] 2018-06-16 09:55
Pinging @aclemons just in case...

**Comment by aclemons** [comment] 2018-06-16 21:22
@rg3 is correct. It should just work even without blacklisting.

I use two blacklist entries for my machines which have multilib:
`gcc-@^(?!http)`
`glibc-(?!zoneinfo)@^(?!http)`

Not strictly necessary, but avoids being prompted to choose a package version.

**Comment by rg3** [comment] 2018-06-17 09:14
I was doing some regular expression tests and it seems the following two blacklist expressions would be pretty solid:

``/gcc-(?!.*multilib)``
``/glibc-(?!zoneinfo)(?!.*multilib)``

So I'm closing the issue. BTW, @aclemons, you may want to watch this repo. It's very low traffic and it would allow you to receive notifications about new open issues like this one.

**Closed as completed by rg3** 2018-06-17 09:14 UTC

**Comment by aclemons** [comment] 2018-06-17 20:25
I can confirm that those regexes also work perfectly.

I've also watched the repo now. Thanks
